CREATE TABLE evento
(
    id                        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome                      VARCHAR(100)     NOT NULL,
    data_inicio               DATE,
    data_fim                  DATE,
    local                     VARCHAR(100)     NOT NULL,
    descricao                 VARCHAR(300)     NOT NULL,
    preco_base_senha          DOUBLE PRECISION NOT NULL,
    quantidade_total_de_senha INTEGER,
    imagens_videos            TEXT[],
    status                    VARCHAR(255)
);